### ISSUE TITLE
Word not completely visible in Amazon Fire Tablet.. May I know the issue?

### ISSUE THREAD

**Issue by sunnymopada** [riontech-xten/StaggeredTextGridView#1]
![screenshot_2016-05-11-07-57-48 1](https://cloud.githubusercontent.com/assets/8909624/15168325/24c3afde-174e-11e6-8293-32269e018497.png)

**Comment by keyuraashra** [comment]
@SanyasiraoM Thanks for posting the issue. Will check and update you on it.

**Comment by riontech-xten** [comment]
Hi @SanyasiraoM,

We are very thankful to you for your collaboration. We have updated latest version of library with resolved bug, which has suggested by you.
