### ISSUE TITLE
Single element is not visible in StaggeredTextGridView

### ISSUE THREAD

**Issue by faisalahmedansari20** [riontech-xten/StaggeredTextGridView#3]
Single element is not visible. However when new element is added. All elements become visible. It only shows views when size is more then one

**Comment by riontech-xten** [comment]
Hi @faisalahmedansari20 i think you use old version 1.0.0, we have already fixed this bug in version 1.0.1. 
Please try with latest version 1.0.1 and let me know if you face same issue in latest version.

Thank you.
